#!/usr/bin/env python3
"""Turn the Sonic Pi recordings in audio/raw/ into game audio.

Reads raw/sfx.wav, raw/battle.wav and raw/title.wav (see base-commander.rb), writes
sfx/*.mp3 and music/*.mp3 for listening, and two files for the build: src/audio/sfx-data.js (SFX_DATA, shared
by the games) and src/audio/music-data.js (MUSIC_DATA, Base Commander only), so a page loads only what it plays.
Needs ffmpeg and numpy. Run: python3 audio/process.py, then ./build.sh
"""
import base64, json, subprocess, sys
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE.parent / "src" / "audio"
SR = 48000
SFX = ["shoot", "laser", "bomb", "hit", "explode", "shield", "pickup", "upgrade",
       "life", "death", "plane", "level_start", "wave_clear", "game_over"]   # order in sfx.wav
MUSIC = {"battle": 64 * 60 / 132, "title": 32 * 60 / 96}   # one pass in seconds, from the Sonic Pi script
QUIET = 10 ** (-60 / 20)   # -60 dBFS counts as silence
MARGIN = 0.5               # seconds kept either side of a loop, so MP3 encoder padding never reaches it


def load(name):
    path = HERE / "raw" / f"{name}.wav"
    if not path.exists():
        sys.exit(f"missing {path}: record it from base-commander.rb first")
    raw = subprocess.run(["ffmpeg", "-v", "error", "-i", str(path), "-f", "f32le", "-ac", "1", "-ar", str(SR), "-"],
                         capture_output=True, check=True).stdout
    return np.frombuffer(raw, np.float32).copy()


def db(v):
    return 20 * np.log10(max(v, 1e-12))


def level(x, target, peak_cap=-1.0):
    """Scale so the loudest 50 ms reaches `target` dB RMS, without the peak passing `peak_cap` dBFS."""
    w = SR // 20
    n = max(1, len(x) // w)
    loudest = max(np.sqrt(np.mean(x[i * w:(i + 1) * w] ** 2)) for i in range(n))
    gain = min(10 ** ((target - db(loudest)) / 20), 10 ** (peak_cap / 20) / np.abs(x).max())
    return x * gain


def encode(x, path, kbps):
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "f32le", "-ar", str(SR), "-ac", "1", "-i", "-",
                    "-codec:a", "libmp3lame", "-b:a", f"{kbps}k", str(path)],
                   input=x.astype(np.float32).tobytes(), check=True)
    return base64.b64encode(path.read_bytes()).decode()


def segments(x, min_gap):
    """(start, end) sample ranges of sound separated by at least `min_gap` seconds of silence."""
    win = SR // 100
    loud = np.flatnonzero(np.abs(x[:len(x) // win * win]).reshape(-1, win).max(1) > QUIET)
    if not len(loud):
        return []
    out, start, prev = [], loud[0], loud[0]
    for i in loud[1:]:
        if (i - prev) * win > min_gap * SR:
            out.append((start * win, (prev + 1) * win))
            start = i
        prev = i
    out.append((start * win, (prev + 1) * win))
    return out


def sfx():
    x = load("sfx")
    segs = segments(x, 0.8)
    if len(segs) != len(SFX):
        sys.exit(f"sfx.wav: found {len(segs)} sounds, expected {len(SFX)} ({', '.join(SFX)}). Re-record with piece = :all_sfx")
    data = {}
    for name, (s, e) in zip(SFX, segs):
        s = max(0, s + int(np.argmax(np.abs(x[s:e]) > QUIET)) - SR // 500)   # 2 ms before the first sound
        e = min(len(x), e + SR // 20)                                      # keep 50 ms of tail
        clip = x[s:e].copy()
        fade = SR * 15 // 1000
        clip[-fade:] *= np.linspace(1, 0, fade)
        data[name] = encode(level(clip, -14), HERE / "sfx" / f"{name}.mp3", 64)
        print(f"  sfx {name:12s} {len(clip) / SR:5.2f} s")
    return data


def music(name, period):
    x = load(name)
    n, m = round(period * SR), round(MARGIN * SR)
    onset = int(np.argmax(np.abs(x) > QUIET))
    a = onset + n - SR // 500   # loop starts 2 ms before the second pass's first downbeat
    if a + n + m > len(x):
        sys.exit(f"{name}.wav is too short: needs 3 full passes, got {len(x) / SR:.1f} s")
    seg = level(x[a - m:a + n + m].copy(), -18)
    # The loop jumps from the end of pass 2 back to its start. Compare the 20 ms before that jump
    # with the 20 ms that really preceded the start: a small difference means no audible click.
    k = SR // 50
    before_end, before_start = seg[m + n - k:m + n], seg[m - k:m]
    mismatch = np.sqrt(np.mean((before_end - before_start) ** 2))
    print(f"  music {name}: loop {period:.3f} s, join mismatch {db(mismatch):.1f} dBFS "
          f"(local level {db(np.sqrt(np.mean(before_start ** 2))):.1f} dBFS)")
    return {"data": encode(seg, HERE / "music" / f"{name}.mp3", 96), "loopStart": MARGIN, "loopEnd": MARGIN + n / SR}


def main():
    print("processing recordings in", HERE / "raw")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, value in [("SFX_DATA", sfx()), ("MUSIC_DATA", {n: music(n, p) for n, p in MUSIC.items()})]:
        path = OUT_DIR / ("sfx-data.js" if name == "SFX_DATA" else "music-data.js")
        path.write_text("// Generated by audio/process.py from the Sonic Pi recordings. Do not edit.\n"
                        f"const {name} = " + json.dumps(value) + ";\n")
        print(f"wrote {path.relative_to(HERE.parent)} ({path.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
